import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Linking from 'expo-linking';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { useApp } from '@/providers/app-provider';

type LegalDocument = 'terms' | 'privacy';
type Section = { title: [string, string]; paragraphs: [string, string][] };

const TERMS: Section[] = [
  { title: ['1. Uso informado', '1. Informed use'], paragraphs: [['Al usar Descubriendo CR aceptás estos Términos. La aplicación ofrece herramientas de descubrimiento, planificación y comunidad; no sustituye el criterio personal ni las instrucciones de autoridades, operadores o guías acreditados.', 'By using Descubriendo CR, you accept these Terms. The app provides discovery, planning, and community tools; it does not replace personal judgment or instructions from authorities, operators, or accredited guides.']] },
  { title: ['2. Horarios, tarifas y movilidad', '2. Schedules, fares, and mobility'], paragraphs: [['Los horarios de buses y ferris, tarifas, disponibilidad, condiciones de ingreso, clima, rutas y enlaces externos son referenciales y pueden cambiar sin aviso. Confirmá siempre con la empresa operadora, la autoridad competente o la fuente oficial antes de viajar, reservar, comprar o iniciar una actividad.', 'Bus and ferry schedules, fares, availability, entry conditions, weather, routes, and external links are for reference and may change without notice. Always confirm with the operator, competent authority, or official source before travelling, booking, purchasing, or starting an activity.'], ['Descubriendo CR no es transportista, agencia de viajes, operador turístico, servicio de emergencia ni autoridad pública. En una emergencia, llamá al 911 o al servicio oficial aplicable.', 'Descubriendo CR is not a carrier, travel agency, tour operator, emergency service, or public authority. In an emergency, call 911 or the applicable official service.']] },
  { title: ['3. Comunidad y uso indebido', '3. Community and misuse'], paragraphs: [['Sos responsable de tu cuenta, publicaciones, fotos, mensajes, reseñas y ubicaciones compartidas. No podés publicar contenido ilegal, engañoso, acosador, que infrinja derechos de terceros, revele ubicaciones sensibles de fauna, promueva actividades peligrosas o perjudique a otras personas, comunidades o ecosistemas.', 'You are responsible for your account, posts, photos, messages, reviews, and shared locations. You may not publish unlawful, misleading, harassing, rights-infringing content, reveal sensitive wildlife locations, promote dangerous activities, or harm people, communities, or ecosystems.'], ['Podés reportar contenido o usuarios y bloquear cuentas desde sus perfiles. Podemos moderar, retirar contenido o restringir cuentas cuando sea necesario para proteger a la comunidad, cumplir la ley o aplicar estos Términos.', 'You can report content or users and block accounts from their profiles. We may moderate or remove content or restrict accounts when needed to protect the community, comply with law, or enforce these Terms.']] },
  { title: ['4. Contenido y servicios de terceros', '4. Third-party content and services'], paragraphs: [['La aplicación puede mostrar enlaces, mapas, información de movilidad, clima, comercios y fotografías de servicios o fuentes de terceros. Cada proveedor aplica sus propios términos y políticas; al abrir un enlace o usar un servicio externo, su relación es directamente con ese proveedor.', 'The app may show links, maps, mobility information, weather, businesses, and photographs from third-party services or sources. Each provider applies its own terms and policies; when you open a link or use an external service, your relationship is directly with that provider.'], ['Algunas fotografías provienen de Wikimedia Commons y se muestran con la atribución, licencia y enlace de fuente disponibles. Respetamos las licencias indicadas para cada obra y solicitamos que nos reportés cualquier uso que considerés incorrecto.', 'Some photographs come from Wikimedia Commons and are shown with available attribution, license, and source link. We respect the licenses shown for each work and ask that you report any use you believe is incorrect.']] },
  { title: ['5. Limitación de responsabilidad', '5. Limitation of liability'], paragraphs: [['En la máxima medida permitida por la ley aplicable, Descubriendo CR no responde por cambios, errores, omisiones, retrasos, cancelaciones, accidentes, pérdidas, daños, decisiones de terceros ni consecuencias de confiar únicamente en información publicada en la aplicación. Verificá datos críticos y seguí las indicaciones oficiales y de seguridad.', 'To the maximum extent permitted by applicable law, Descubriendo CR is not liable for changes, errors, omissions, delays, cancellations, accidents, losses, damages, third-party decisions, or consequences of relying solely on information published in the app. Verify critical information and follow official and safety guidance.']] },
  { title: ['6. Cambios y legislación aplicable', '6. Changes and governing law'], paragraphs: [['Podemos actualizar estos Términos cuando cambien la aplicación, los servicios o los requisitos legales. La versión vigente se publicará en esta pantalla. Se aplica la legislación de Costa Rica, sin perjuicio de normas imperativas que resulten aplicables.', 'We may update these Terms when the app, services, or legal requirements change. The current version will be published on this screen. Costa Rican law applies, without prejudice to mandatory rules that may apply.']] },
];

const PRIVACY: Section[] = [
  { title: ['1. Alcance', '1. Scope'], paragraphs: [['Esta política explica cómo Descubriendo CR trata datos personales al usar la aplicación. Se elaboró considerando la Ley N.° 8968 de Costa Rica sobre protección de datos personales; no reemplaza una revisión jurídica específica para la operación comercial de la plataforma.', 'This policy explains how Descubriendo CR processes personal data when you use the app. It was prepared with Costa Rica’s Personal Data Protection Law No. 8968 in mind; it does not replace a legal review specific to the platform’s commercial operation.']] },
  { title: ['2. Datos que tratamos', '2. Data we process'], paragraphs: [['Podemos tratar datos de cuenta y perfil (correo, nombre de usuario, nombre, foto, biografía y correo de contacto), contenido que decidís publicar (fotos, audio, mensajes, comentarios, reseñas y ubicaciones compartidas), preferencias de viaje, token de notificaciones, estado de compras o suscripciones y datos de ubicación cuando otorgás permiso para funciones cercanas, navegación o al compartir una ubicación.', 'We may process account and profile data (email, username, name, photo, bio, and contact email), content you choose to publish (photos, audio, messages, comments, reviews, and shared locations), travel preferences, notification token, purchase or subscription status, and location data when you grant permission for nearby features, navigation, or sharing a location.'], ['Las fotos compartidas se optimizan antes de cargarse; la aplicación busca eliminar sus metadatos de ubicación. No compartás información personal o de terceros que no sea necesaria.', 'Shared photos are optimized before upload; the app seeks to remove their location metadata. Do not share personal or third-party information that is not necessary.']] },
  { title: ['3. Finalidades', '3. Purposes'], paragraphs: [['Usamos los datos para crear y proteger cuentas, prestar las funciones solicitadas, mostrar y moderar contenido comunitario, guardar preferencias y favoritos, enviar comunicaciones dentro de la aplicación, mejorar la estabilidad y prevenir fraude, abuso o incumplimientos.', 'We use data to create and protect accounts, provide requested features, show and moderate community content, save preferences and favorites, deliver in-app communications, improve reliability, and prevent fraud, abuse, or violations.']] },
  { title: ['4. Datos públicos y ubicación', '4. Public data and location'], paragraphs: [['El perfil, publicaciones, fotos, comentarios, reseñas y ubicaciones que decidas compartir pueden ser visibles para otras personas según la función utilizada. Revisá cada publicación antes de enviarla. La ubicación actual se usa para funciones como destinos cercanos y planificación; no afirmamos que sea exacta ni apta para emergencias.', 'Your profile, posts, photos, comments, reviews, and locations you choose to share may be visible to others depending on the feature used. Review each post before submitting it. Current location is used for features such as nearby destinations and planning; we do not claim it is exact or suitable for emergencies.']] },
  { title: ['5. Encargados y servicios externos', '5. Processors and external services'], paragraphs: [['Usamos Supabase para autenticación, base de datos y almacenamiento; Expo para compilaciones y notificaciones; Google para OAuth y Google Play; OpenStreetMap o Mapbox para mapas; OpenWeather para clima; y Stripe para pagos web. Esos servicios pueden tratar los datos necesarios para prestar cada función bajo sus propias políticas. No vendemos datos personales.', 'We use Supabase for authentication, database, and storage; Expo for builds and notifications; Google for OAuth and Google Play; OpenStreetMap or Mapbox for maps; OpenWeather for weather; and Stripe for web payments. These services may process the data required for each feature under their own policies. We do not sell personal data.']] },
  { title: ['6. Conservación y seguridad', '6. Retention and security'], paragraphs: [['Conservamos los datos mientras tu cuenta o el contenido permanezcan activos, o durante el tiempo razonablemente necesario para prestar el servicio, resolver disputas, prevenir abuso y cumplir obligaciones aplicables. Aplicamos controles de acceso y medidas técnicas acordes con la plataforma; ningún sistema puede garantizar seguridad absoluta.', 'We retain data while your account or content remains active, or for the time reasonably necessary to provide the service, resolve disputes, prevent abuse, and meet applicable obligations. We apply access controls and technical measures appropriate for the platform; no system can guarantee absolute security.']] },
  { title: ['7. Tus derechos, eliminación y contacto', '7. Your rights, deletion, and contact'], paragraphs: [['Podés solicitar acceso o rectificación de tus datos y revocar permisos desde los ajustes del dispositivo. La opción “Eliminar cuenta y datos” del perfil elimina de forma definitiva tus credenciales, perfil, publicaciones, mensajes, fotos, reseñas y demás datos asociados. La misma solicitud está disponible en la página web /delete-account.', 'You may request access to or correction of your data and revoke device permissions in device settings. The “Delete account and data” option in your profile permanently deletes your credentials, profile, posts, messages, photos, reviews, and other associated data. The same request is available on the /delete-account web page.']] },
  { title: ['8. Actualizaciones', '8. Updates'], paragraphs: [['Podemos actualizar esta política al cambiar el tratamiento de datos, los proveedores o la ley. Publicaremos la versión vigente aquí.', 'We may update this policy when data processing, providers, or law changes. We will publish the current version here.']] },
];

export function LegalDocumentScreen({ document }: { document: LegalDocument }) {
  const { language } = useApp();
  const router = useRouter();
  const isTerms = document === 'terms';
  const sections = isTerms ? TERMS : PRIVACY;
  const title = language === 'es' ? (isTerms ? 'Términos y condiciones' : 'Política de privacidad') : (isTerms ? 'Terms and conditions' : 'Privacy policy');
  const updated = language === 'es' ? 'Última actualización: 4 de septiembre de 2026' : 'Last updated: September 4, 2026';
  const legalEmail = process.env.EXPO_PUBLIC_LEGAL_CONTACT_EMAIL?.trim() || 'jose17mp3@gmail.com';

  return (
    <SafeAreaView className="flex-1 bg-ui-background dark:bg-ui-dark-background" edges={['top', 'bottom']}>
      <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 48 }} showsVerticalScrollIndicator={false}>
        <Pressable accessibilityLabel={language === 'es' ? 'Volver' : 'Back'} accessibilityRole="button" className="mb-6 h-11 w-11 items-center justify-center rounded-full bg-ui-surface dark:bg-ui-dark-surface" onPress={() => router.back()}>
          <MaterialCommunityIcons color="#0B6B4F" name="arrow-left" size={23} />
        </Pressable>
        <Text className="text-3xl font-black leading-9 text-ui-text dark:text-ui-dark-text">{title}</Text>
        <Text className="mt-2 text-xs font-bold text-ui-text-muted dark:text-ui-dark-text-muted">{updated}</Text>
        {sections.map((section) => (
          <View className="mt-7" key={section.title[0]}>
            <Text className="text-lg font-black text-ui-text dark:text-ui-dark-text">{section.title[language === 'es' ? 0 : 1]}</Text>
            {section.paragraphs.map((paragraph) => <Text className="mt-3 text-sm leading-6 text-ui-text-muted dark:text-ui-dark-text-muted" key={paragraph[0]}>{paragraph[language === 'es' ? 0 : 1]}</Text>)}
          </View>
        ))}
        {document === 'privacy' && legalEmail ? <Pressable accessibilityRole="link" className="mt-7 self-start rounded-control bg-ui-primary px-4 py-3 dark:bg-ui-dark-primary" onPress={() => void Linking.openURL(`mailto:${legalEmail}`)}><Text className="font-black text-white dark:text-ui-dark-background">{language === 'es' ? `Contactar: ${legalEmail}` : `Contact: ${legalEmail}`}</Text></Pressable> : null}
      </ScrollView>
    </SafeAreaView>
  );
}
