import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useQuery } from '@tanstack/react-query';
import * as Linking from 'expo-linking';
import { useEffect, useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';

import { getBusRoutes, type BusRoute } from '@/lib/bus-routes';
import { ferryRoutes, getFerryRoutes } from '@/lib/logistics';
import { useApp } from '@/providers/app-provider';

type ViewName = 'home' | 'buses' | 'ferries';

export default function LogisticsScreen() {
  const { formatPrice, language } = useApp();
  const { reset } = useLocalSearchParams<{ reset?: string }>();
  const [view, setView] = useState<ViewName>('home');
  const [query, setQuery] = useState('');
  const [openRoute, setOpenRoute] = useState<string | null>(null);
  const [group, setGroup] = useState<'tourist' | 'cantonal'>('tourist');
  useEffect(() => { if (reset) { setView('home'); setQuery(''); setOpenRoute(null); setGroup('tourist'); } }, [reset]);
  const buses = useQuery({ queryKey: ['bus-routes', group, query], queryFn: () => getBusRoutes(query, group), enabled: view === 'buses', staleTime: 5 * 60 * 1000 });
  const ferries = useQuery({ queryKey: ['ferry-routes'], queryFn: getFerryRoutes, enabled: view === 'ferries', staleTime: 30 * 60 * 1000 });
  const title = language === 'es' ? 'Buses y Ferrys' : 'Buses & Ferries';

  return <ScrollView className="flex-1 bg-ui-background dark:bg-ui-dark-background" contentContainerStyle={{ paddingBottom: 44 }} showsVerticalScrollIndicator={false}>
    <View className="border-b border-ui-border bg-ui-surface px-5 pb-6 pt-7 dark:border-ui-dark-border dark:bg-ui-dark-surface">
      {view !== 'home' ? <Pressable accessibilityRole="button" className="mb-5 flex-row items-center self-start" onPress={() => setView('home')}><MaterialCommunityIcons name="arrow-left" size={22} color="#0077A8" /><Text className="ml-2 font-black text-caribbean-600">{title}</Text></Pressable> : null}
      <View className="flex-row items-center"><View className="h-14 w-14 items-center justify-center rounded-2xl bg-caribbean-50 dark:bg-caribbean-900"><MaterialCommunityIcons name={view === 'ferries' ? 'ferry' : 'bus'} size={31} color="#0077A8" /></View><View className="ml-4 flex-1"><Text className="text-3xl font-extrabold tracking-tight text-ui-text dark:text-ui-dark-text">{view === 'home' ? title : view === 'buses' ? (language === 'es' ? 'Rutas de interés turístico' : 'Tourist bus routes') : (language === 'es' ? 'Horarios Ferrys' : 'Ferry schedules')}</Text><Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">{view === 'buses' ? (language === 'es' ? 'Ida, regreso, tarifa y días de operación.' : 'Outbound, return, fare and operating days.') : (language === 'es' ? 'Consultá rutas y salidas verificadas.' : 'Check verified routes and departures.')}</Text></View></View>
    </View>

    {view === 'home' ? <View className="gap-4 px-5 pt-6"><MainCard icon="bus" subtitle="Rutas seleccionadas para viajar por Costa Rica" title="Rutas turísticas" onPress={() => { setGroup('tourist'); setView('buses'); }} /><MainCard icon="bus" subtitle="Rutas locales dentro del cantón" title="Rutas cantonales" onPress={() => { setGroup('cantonal'); setView('buses'); }} /><MainCard icon="ferry" subtitle={language === 'es' ? 'Cruces del Golfo de Nicoya' : 'Gulf of Nicoya crossings'} title={language === 'es' ? 'Horarios Ferrys' : 'Ferry schedules'} onPress={() => setView('ferries')} /></View> : null}

    {view === 'buses' ? <View className="px-5 pt-5"><TextInput accessibilityLabel={language === 'es' ? 'Buscar rutas turísticas de bus' : 'Search tourist bus routes'} className="rounded-control bg-ui-muted px-4 py-3 text-ui-text dark:bg-ui-dark-muted dark:text-ui-dark-text" onChangeText={(value) => { setQuery(value); setOpenRoute(null); }} placeholder={language === 'es' ? 'Buscar San José, La Fortuna, Cahuita...' : 'Search San José, La Fortuna, Cahuita...'} placeholderTextColor="#68737A" value={query} />
      <View className="mt-4 rounded-2xl border border-caribbean-500/30 bg-caribbean-50 p-4 dark:bg-caribbean-900/30"><Text className="font-black text-caribbean-700 dark:text-caribbean-100">{language === 'es' ? 'Horarios para viajeros' : 'Timetables for travellers'}</Text><Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">{language === 'es' ? 'Solo se publican rutas con tarifa y horarios de semana, sábado y domingo. Confirmá antes de viajar.' : 'Only routes with a fare and weekday, Saturday and Sunday schedules are published. Confirm before travelling.'}</Text></View>
      {buses.isPending ? <Text className="mt-5 text-ui-text-muted dark:text-ui-dark-text-muted">{language === 'es' ? 'Cargando rutas turísticas...' : 'Loading tourist routes...'}</Text> : null}
      {buses.isError ? <Text className="mt-5 text-danger-600">{language === 'es' ? 'No se pudieron cargar las rutas. Intentá nuevamente.' : 'Routes could not be loaded. Please try again.'}</Text> : null}
      {buses.data?.map((route) => <BusRouteCard formatPrice={formatPrice} key={route.source_key} open={openRoute === route.source_key} route={route} toggle={() => setOpenRoute((current) => current === route.source_key ? null : route.source_key)} />)}
      {buses.data && buses.data.length === 0 ? <View className="mt-5 rounded-2xl bg-ui-muted p-4 dark:bg-ui-dark-muted"><Text className="font-black text-ui-text dark:text-ui-dark-text">{language === 'es' ? 'Catálogo en actualización' : 'Catalogue being updated'}</Text><Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">{language === 'es' ? 'No publicamos rutas si falta un horario o una tarifa verificable.' : 'We do not publish routes with a missing schedule or verifiable fare.'}</Text></View> : null}
    </View> : null}

    {view === 'ferries' ? <View className="px-5 pt-2">{(ferries.data ?? ferryRoutes).map((route) => <View className="mt-4 rounded-card border border-ui-border bg-ui-surface p-5 dark:border-ui-dark-border dark:bg-ui-dark-surface" key={route.id}><Text className="text-lg font-black text-ui-text dark:text-ui-dark-text">{route.route}</Text><Text className="mt-1 font-bold text-ui-secondary dark:text-ui-dark-secondary">{route.operator}</Text><ScheduleRow label="Lunes a viernes" times={route.schedules.weekday} /><ScheduleRow label="Sábado" times={route.schedules.saturday} /><ScheduleRow label="Domingo" times={route.schedules.sunday} />{route.scheduleNote ? <Text className="mt-3 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">{route.scheduleNote}</Text> : null}<Text className="mt-4 font-black text-ui-text dark:text-ui-dark-text">Adulto: {route.adultFare === null ? 'No publicada' : formatPrice(route.adultFare)}</Text>{route.childFare !== null ? <Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">Menor: {formatPrice(route.childFare)}</Text> : null}{route.vehicleFare !== null ? <Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">Vehículo liviano: {formatPrice(route.vehicleFare)}</Text> : null}{route.terminalName ? <View className="mt-4 rounded-xl bg-ui-muted p-3 dark:bg-ui-dark-muted"><Text className="font-bold text-ui-text dark:text-ui-dark-text">Terminal: {route.terminalName}</Text>{route.wazeUrl ? <Pressable accessibilityRole="link" className="mt-2 self-start" onPress={() => void Linking.openURL(route.wazeUrl!)}><Text className="font-black text-caribbean-700 dark:text-caribbean-100">Abrir en Waze</Text></Pressable> : null}</View> : null}<View className="mt-4 flex-row gap-4"><Pressable accessibilityRole="link" onPress={() => void Linking.openURL(route.scheduleSourceUrl)}><Text className="font-black text-caribbean-700 dark:text-caribbean-100">Ver horario</Text></Pressable>{route.fareSourceUrl ? <Pressable accessibilityRole="link" onPress={() => void Linking.openURL(route.fareSourceUrl!)}><Text className="font-black text-caribbean-700 dark:text-caribbean-100">Tarifa ARESEP</Text></Pressable> : null}</View>{route.validUntil ? <Text className="mt-2 text-xs text-ui-text-muted dark:text-ui-dark-text-muted">Vigencia publicada: {route.validUntil}</Text> : null}</View>)}</View> : null}
  </ScrollView>;
}

function MainCard({ icon, subtitle, title, onPress }: { icon: 'bus' | 'ferry'; subtitle: string; title: string; onPress: () => void }) {
  return <Pressable accessibilityRole="button" className="flex-row items-center rounded-card border border-ui-border bg-ui-surface p-5 active:opacity-75 dark:border-ui-dark-border dark:bg-ui-dark-surface" onPress={onPress}><View className="h-14 w-14 items-center justify-center rounded-2xl bg-caribbean-500"><MaterialCommunityIcons name={icon} size={30} color="white" /></View><View className="ml-4 flex-1"><Text className="text-xl font-black text-ui-text dark:text-ui-dark-text">{title}</Text><Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">{subtitle}</Text></View><MaterialCommunityIcons name="chevron-right" size={26} color="#0077A8" /></Pressable>;
}

function BusRouteCard({ formatPrice, open, route, toggle }: { formatPrice: (value: number) => string; open: boolean; route: BusRoute; toggle: () => void }) {
  return <View className="mt-4 overflow-hidden rounded-card border border-ui-border bg-ui-surface dark:border-ui-dark-border dark:bg-ui-dark-surface"><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} className="flex-row items-center p-5" onPress={toggle}><View className="h-11 w-11 items-center justify-center rounded-xl bg-caribbean-500/15"><MaterialCommunityIcons name="bus" size={25} color="#0077A8" /></View><View className="ml-3 flex-1"><Text className="text-lg font-black text-ui-text dark:text-ui-dark-text">{route.route_name}</Text><Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">{route.origin_city} → {route.destination_city}</Text></View><MaterialCommunityIcons name={open ? 'chevron-up' : 'chevron-down'} size={25} color="#0077A8" /></Pressable>{open ? <View className="border-t border-ui-border p-5 dark:border-ui-dark-border"><Text className="font-black text-ui-text dark:text-ui-dark-text">Tarifa: {route.fare_crc === null ? 'No publicada' : formatPrice(route.fare_crc)}</Text><Text className="mt-1 text-xs text-ui-text-muted dark:text-ui-dark-text-muted">{route.fare_crc === null ? 'No se publicó una tarifa para esta ruta.' : route.fare_kind === 'estimated' ? 'Tarifa estimada; confirmá antes de viajar.' : 'Tarifa publicada por la fuente.'}</Text><ScheduleRow label="Lunes a viernes" times={route.schedules.weekday} /><ScheduleRow label="Sábado" times={route.schedules.saturday} /><ScheduleRow label="Domingo" times={route.schedules.sunday} />{route.terminal_name ? <View className="mt-4 rounded-xl bg-ui-muted p-3 dark:bg-ui-dark-muted"><Text className="font-bold text-ui-text dark:text-ui-dark-text">Terminal: {route.terminal_name}</Text>{route.terminal_waze_url ? <Pressable accessibilityRole="link" className="mt-2 self-start" onPress={() => void Linking.openURL(route.terminal_waze_url!)}><Text className="font-black text-caribbean-700 dark:text-caribbean-100">Abrir en Waze</Text></Pressable> : null}</View> : null}<Pressable accessibilityRole="link" className="mt-4 self-start" onPress={() => void Linking.openURL(route.source_url)}><Text className="font-black text-caribbean-700 dark:text-caribbean-100">Ver fuente y confirmar horario</Text></Pressable><Text className="mt-2 text-xs text-ui-text-muted dark:text-ui-dark-text-muted">Verificado: {new Date(route.last_verified_at).toLocaleDateString('es-CR')}</Text></View> : null}</View>;
}

function ScheduleRow({ label, times }: { label: string; times: string[] }) {
  return <View className="mt-4"><Text className="font-black text-ui-text dark:text-ui-dark-text">{label}</Text>{times.length ? <View className="mt-2 flex-row flex-wrap gap-2">{times.map((time) => <View className="rounded-full bg-ui-muted px-3 py-1.5 dark:bg-ui-dark-muted" key={`${label}-${time}`}><Text className="text-sm font-bold text-ui-text dark:text-ui-dark-text">{time}</Text></View>)}</View> : <Text className="mt-1 text-sm italic text-ui-text-muted dark:text-ui-dark-text-muted">No publicado</Text>}</View>;
}
