import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';

import { BUS_ROUTE_PAGE_SIZE, getBusRoutes, type BusRoute } from '@/lib/bus-routes';
import { ferryRoutes } from '@/lib/logistics';
import { useApp } from '@/providers/app-provider';

type ViewName = 'home' | 'buses' | 'ferries';

export default function LogisticsScreen() {
  const { formatPrice, language } = useApp();
  const [view, setView] = useState<ViewName>('home');
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(0);
  const [openRoute, setOpenRoute] = useState<string | null>(null);
  const buses = useQuery({ queryKey: ['aresep-bus-routes', query, page], queryFn: () => getBusRoutes(query, page), staleTime: 5 * 60 * 1000, enabled: view === 'buses' });
  const title = language === 'es' ? 'Buses y Ferrys' : 'Buses & Ferries';
  const totalPages = Math.max(1, Math.ceil((buses.data?.total ?? 0) / BUS_ROUTE_PAGE_SIZE));
  const updateQuery = (value: string) => { setQuery(value); setPage(0); setOpenRoute(null); };

  return <ScrollView className="flex-1 bg-ui-background dark:bg-ui-dark-background" contentContainerStyle={{ paddingBottom: 44 }} showsVerticalScrollIndicator={false}>
    <View className="border-b border-ui-border bg-ui-surface px-5 pb-6 pt-7 dark:border-ui-dark-border dark:bg-ui-dark-surface">
      {view !== 'home' ? <Pressable accessibilityRole="button" className="mb-5 flex-row items-center self-start" onPress={() => setView('home')}><MaterialCommunityIcons name="arrow-left" size={22} color="#0077A8" /><Text className="ml-2 font-black text-caribbean-600">{title}</Text></Pressable> : null}
      <View className="flex-row items-center"><View className="h-14 w-14 items-center justify-center rounded-2xl bg-caribbean-50 dark:bg-caribbean-900"><MaterialCommunityIcons name={view === 'ferries' ? 'ferry' : 'bus'} size={31} color="#0077A8" /></View><View className="ml-4 flex-1"><Text className="text-3xl font-extrabold tracking-tight text-ui-text dark:text-ui-dark-text">{view === 'home' ? title : view === 'buses' ? (language === 'es' ? 'Rutas y tarifas de bus' : 'Bus routes & fares') : (language === 'es' ? 'Horarios Ferrys' : 'Ferry schedules')}</Text><Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">{view === 'buses' ? 'Información oficial publicada por ARESEP.' : (language === 'es' ? 'Consultá rutas y salidas verificadas.' : 'Check verified routes and departures.')}</Text></View></View>
    </View>

    {view === 'home' ? <View className="gap-4 px-5 pt-6"><MainCard icon="bus" subtitle={language === 'es' ? 'Tarifas y datos oficiales de ARESEP' : 'Official ARESEP fares and route data'} title={language === 'es' ? 'Rutas de bus' : 'Bus routes'} onPress={() => setView('buses')} /><MainCard icon="ferry" subtitle={language === 'es' ? 'Cruces del Golfo de Nicoya' : 'Gulf of Nicoya crossings'} title={language === 'es' ? 'Horarios Ferrys' : 'Ferry schedules'} onPress={() => setView('ferries')} /></View> : null}

    {view === 'buses' ? <View className="px-5 pt-5"><TextInput accessibilityLabel={language === 'es' ? 'Buscar rutas de bus ARESEP' : 'Search ARESEP bus routes'} className="rounded-control bg-ui-muted px-4 py-3 text-ui-text dark:bg-ui-dark-muted dark:text-ui-dark-text" onChangeText={updateQuery} placeholder={language === 'es' ? 'Buscar ruta, ramal o destino...' : 'Search route, branch or destination...'} placeholderTextColor="#68737A" value={query} />
      <View className="mt-4 rounded-2xl border border-caribbean-500/30 bg-caribbean-50 p-4 dark:bg-caribbean-900/30"><View className="flex-row items-center"><MaterialCommunityIcons name="shield-check-outline" size={21} color="#0077A8" /><Text className="ml-2 font-black text-caribbean-700 dark:text-caribbean-100">Datos oficiales de ARESEP</Text></View><Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">ARESEP publica tarifas, ruta, ramal, fraccionamiento, operador, resolución y datos de recorrido. No publica horarios operativos ni coordenadas de terminal para Waze.</Text></View>
      {buses.isPending ? <Text className="mt-5 text-ui-text-muted dark:text-ui-dark-text-muted">{language === 'es' ? 'Cargando rutas oficiales...' : 'Loading official routes...'}</Text> : null}
      {buses.isError ? <Text className="mt-5 text-danger-600">No se pudieron cargar las rutas oficiales. Intentá nuevamente.</Text> : null}
      {buses.data?.routes.map((route) => <BusRouteCard formatPrice={formatPrice} key={route.source_key} open={openRoute === route.source_key} route={route} toggle={() => setOpenRoute((current) => current === route.source_key ? null : route.source_key)} />)}
      {buses.data && buses.data.total === 0 ? <Text className="mt-5 text-ui-text-muted dark:text-ui-dark-text-muted">No hay resultados para esta búsqueda.</Text> : null}
      {buses.data && buses.data.total > BUS_ROUTE_PAGE_SIZE ? <View className="mb-2 mt-5 flex-row items-center justify-between"><Pressable accessibilityRole="button" className="rounded-xl bg-ui-muted px-4 py-3 disabled:opacity-40 dark:bg-ui-dark-muted" disabled={page === 0} onPress={() => { setPage((value) => Math.max(0, value - 1)); setOpenRoute(null); }}><Text className="font-black text-ui-text dark:text-ui-dark-text">Anterior</Text></Pressable><Text className="text-sm font-bold text-ui-text-muted dark:text-ui-dark-text-muted">{page + 1} / {totalPages}</Text><Pressable accessibilityRole="button" className="rounded-xl bg-caribbean-600 px-4 py-3 disabled:opacity-40" disabled={page + 1 >= totalPages} onPress={() => { setPage((value) => value + 1); setOpenRoute(null); }}><Text className="font-black text-white">Siguiente</Text></Pressable></View> : null}
    </View> : null}

    {view === 'ferries' ? <View className="px-5 pt-2">{ferryRoutes.map((route) => <View className="mt-4 rounded-card border border-ui-border bg-ui-surface p-5 dark:border-ui-dark-border dark:bg-ui-dark-surface" key={route.id}><Text className="text-lg font-black text-ui-text dark:text-ui-dark-text">{route.route}</Text><Text className="mt-1 font-bold text-ui-secondary dark:text-ui-dark-secondary">{route.operator}</Text><Text className="mt-4 text-sm font-bold text-ui-text-muted dark:text-ui-dark-text-muted">{language === 'es' ? 'Salidas' : 'Departures'}</Text><View className="mt-2 flex-row flex-wrap gap-2">{route.departures.map((time) => <View className="rounded-full bg-ui-muted px-3 py-1.5 dark:bg-ui-dark-muted" key={time}><Text className="font-bold text-ui-text dark:text-ui-dark-text">{time}</Text></View>)}</View><Text className="mt-4 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">{language === 'es' ? 'Adulto' : 'Adult'}: {formatPrice(route.adultFare)}</Text></View>)}</View> : null}
  </ScrollView>;
}

function MainCard({ icon, subtitle, title, onPress }: { icon: 'bus' | 'ferry'; subtitle: string; title: string; onPress: () => void }) {
  return <Pressable accessibilityRole="button" className="flex-row items-center rounded-card border border-ui-border bg-ui-surface p-5 active:opacity-75 dark:border-ui-dark-border dark:bg-ui-dark-surface" onPress={onPress}><View className="h-14 w-14 items-center justify-center rounded-2xl bg-caribbean-500"><MaterialCommunityIcons name={icon} size={30} color="white" /></View><View className="ml-4 flex-1"><Text className="text-xl font-black text-ui-text dark:text-ui-dark-text">{title}</Text><Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">{subtitle}</Text></View><MaterialCommunityIcons name="chevron-right" size={26} color="#0077A8" /></Pressable>;
}

function BusRouteCard({ formatPrice, open, route, toggle }: { formatPrice: (value: number) => string; open: boolean; route: BusRoute; toggle: () => void }) {
  const codes = [route.codigo_ruta, route.codigo_ramal, route.codigo_fraccionamiento].filter(Boolean).join(' · ');
  return <View className="mt-4 overflow-hidden rounded-card border border-ui-border bg-ui-surface dark:border-ui-dark-border dark:bg-ui-dark-surface"><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} className="flex-row items-center p-5" onPress={toggle}><View className="h-11 w-11 items-center justify-center rounded-xl bg-caribbean-500/15"><MaterialCommunityIcons name="bus" size={25} color="#0077A8" /></View><View className="ml-3 flex-1"><Text className="text-lg font-black text-ui-text dark:text-ui-dark-text">{route.route_name}</Text><Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">{codes || 'Código no publicado'}</Text></View><MaterialCommunityIcons name={open ? 'chevron-up' : 'chevron-down'} size={25} color="#0077A8" /></Pressable>{open ? <View className="border-t border-ui-border p-5 dark:border-ui-dark-border"><Text className="font-black text-ui-text dark:text-ui-dark-text">Tarifa regular: {route.fare_crc === null ? 'No publicada' : formatPrice(route.fare_crc)}</Text>{route.senior_fare_crc !== null ? <Text className="mt-1 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">Tarifa adulto mayor: {formatPrice(route.senior_fare_crc)}</Text> : null}{route.company_name ? <Text className="mt-4 font-bold text-ui-text dark:text-ui-dark-text">Operador</Text> : null}{route.company_name ? <Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">{route.company_name}</Text> : null}{route.distance_km !== null ? <Text className="mt-4 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">Distancia promedio: {route.distance_km.toFixed(2)} km</Text> : null}{route.resolution ? <Text className="mt-2 text-sm text-ui-text-muted dark:text-ui-dark-text-muted">Resolución: {route.resolution}{route.effective_date ? ` · Vigente desde ${new Date(`${route.effective_date}T00:00:00`).toLocaleDateString('es-CR')}` : ''}</Text> : null}<View className="mt-4 rounded-xl bg-ui-muted p-3 dark:bg-ui-dark-muted"><Text className="text-sm font-bold text-ui-text dark:text-ui-dark-text">Horarios y terminal</Text><Text className="mt-1 text-sm leading-5 text-ui-text-muted dark:text-ui-dark-text-muted">ARESEP no publica esos datos en su catálogo abierto; por transparencia no se muestran valores estimados.</Text></View><Text className="mt-4 text-xs text-ui-text-muted dark:text-ui-dark-text-muted">Fuente: ARESEP · actualización registrada {new Date(route.source_updated_at).toLocaleDateString('es-CR')}</Text></View> : null}</View>;
}
