import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import vm from 'node:vm';

const module = { exports: {} };
vm.runInNewContext(ts.transpileModule(readFileSync('src/lib/compass.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, { exports: module.exports });
const { headingDegrees, normalizeHeading, smoothHeading } = module.exports;
assert.equal(normalizeHeading(-90), 270);
assert.equal(normalizeHeading(720), 0);
assert.equal(smoothHeading(null, 359), 359);
assert.equal(smoothHeading(359, 1), 359.7);
assert.ok(Math.abs(smoothHeading(1, 359) - 0.3) < Number.EPSILON);
assert.equal(smoothHeading(719, 1), 719.7);
assert.equal(smoothHeading(40, NaN), 40);
assert.equal(smoothHeading(null, Infinity), null);
for (const angle of [0, 90, 180, 270]) assert.equal(smoothHeading(angle, angle), angle);
assert.equal(headingDegrees({ trueHeading: 45, magHeading: 40 }), 45);
assert.equal(headingDegrees({ trueHeading: -1, magHeading: 40 }), 40);
assert.equal(headingDegrees({ trueHeading: NaN, magHeading: NaN }), null);
assert.equal(headingDegrees({ trueHeading: 360, magHeading: 0 }), 0);
const header = readFileSync('src/components/global-header.tsx', 'utf8');
const screen = readFileSync('src/app/compass.tsx', 'utf8');
const hook = readFileSync('src/hooks/use-compass.ts', 'utf8');
assert(header.indexOf("'Compra USD'") < header.indexOf("router.push('/compass')"));
assert(header.indexOf("router.push('/compass')") < header.indexOf('visitorOptions.map'));
assert(screen.includes('<MapCanvas expanded urban'), 'Compass uses the urban map');
assert(readFileSync('src/components/explore/map-canvas.native.tsx', 'utf8').includes('zoomLevel: 17'), 'Compass map zooms into the current location');
assert(!hook.includes('watchPositionAsync'), 'Compass must not duplicate the app-wide location watcher');
console.log('Compass: wraparound, smoothing, heading validity and button placement passed.');
