import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/lib/logistics.ts', import.meta.url), 'utf8');
const optionsSource = await readFile(new URL('../src/lib/app-options.ts', import.meta.url), 'utf8');
const exploreSource = await readFile(new URL('../src/app/(tabs)/explore.tsx', import.meta.url), 'utf8');
assert.match(source, /reducedMobility[\s\S]*fácil\|facil/);
assert.match(source, /Promise\.all\([\s\S]*getWeather[\s\S]*getNearbyFoodService[\s\S]*getTravelMinutes/);
assert.match(source, /saveOfflinePack\(destinations: Destination\[\], dayPlan\?/);
assert.match(source, /requires_sinac_booking,sinac_booking_url/);
assert.doesNotMatch(source, /return \(preferred\.length \? preferred : candidates\)\.slice/);
assert.match(source, /export async function buildTripPlan/);
assert.match(source, /export function buildOfflineTripPlan/);
assert.match(source, /while \(stops\.length < 4 && remainingBudget >= 0\)/);
assert.match(source, /directions-matrix\/v1\/mapbox/);
assert.match(source, /isNatureDestination[\s\S]*setHours\(16, 0, 0, 0\)/);
assert.match(source, /mealBudgetPerPerson[\s\S]*20500/);
assert.match(source, /estimatedTotalCrc: mealCostCrc/);
assert.match(optionsSource, /getAppOptions\("destination_category"\)/);
assert.match(optionsSource, /categories\.filter\(\(option\) => option\.parent_id === null\)/);
assert.match(exploreSource, /categories\.length > 3/);
assert.match(exploreSource, /value\.length === 3/);
console.log('Planner builds one accessible, actionable, offline-capable day plan.');
