-- Replaces visit information imported from the mistakenly supplied file with qwqewrr.json.
-- Restores the prior 23 rows from their backup, then applies the 48 verified replacement records.
begin;

create schema if not exists private;

create table if not exists private.destination_visit_info_backups (
  batch_key text not null,
  destination_id uuid not null,
  snapshot jsonb not null,
  backed_up_at timestamptz not null default now(),
  primary key (batch_key, destination_id)
);
revoke all on table private.destination_visit_info_backups from public, anon, authenticated;

create temporary table correct_destination_visit_info_payload (
  destination_id uuid primary key,
  expected_name text not null,
  source_id text not null,
  tipo_acceso text,
  estado_camino text,
  duracion_estimada text,
  mejor_temporada text,
  recomendaciones_seguridad text,
  enlace_web text,
  reserva_requerida boolean,
  horario_atencion text,
  estacionamiento text,
  servicios_sanitarios boolean,
  restaurante_o_soda boolean,
  acceso_para_discapacitados text,
  se_permite_mascotas text,
  camping_permitido text,
  codigo_local text,
  relevancia_cultural text
) on commit drop;

insert into correct_destination_visit_info_payload
select *
from jsonb_to_recordset($correct_visit_info$[
  {
    "destination_id": "da9f4b97-48c3-4d1b-a922-b1ce39ba8de9",
    "expected_name": "Aguas Termales de Tabacón",
    "source_id": "nuevo_1",
    "tipo_acceso": "Carro normal (acceso pavimentado hasta el complejo)",
    "estado_camino": "Carretera pavimentada y accesos internos en buen estado",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, hidratación, no correr cerca de las piscinas, supervisión de niños",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "10:00 a.m. - 10:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL001",
    "relevancia_cultural": "Complejo termal de clase mundial, ícono del turismo de bienestar en la Zona Norte"
  },
  {
    "destination_id": "a850c60f-2007-4032-86e0-c491fe66cf27",
    "expected_name": "Basílica de Nuestra Señora de los Ángeles",
    "source_id": "nuevo_2",
    "tipo_acceso": "Carro normal (acceso urbano pavimentado)",
    "estado_camino": "Calles pavimentadas en Cartago",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Todo el año (especialmente 2 de agosto)",
    "recomendaciones_seguridad": "Cuidado con pertenencias en zonas concurridas, calzado cómodo para caminar",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "6:00 a.m. - 7:00 p.m.",
    "estacionamiento": "Sí (público cercano)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "CU001",
    "relevancia_cultural": "Principal centro religioso de Costa Rica, sede de la devoción a la Virgen de los Ángeles"
  },
  {
    "destination_id": "4f625302-a1db-486a-a387-a716bd6a6516",
    "expected_name": "Catarata La Diana",
    "source_id": "nuevo_3",
    "tipo_acceso": "4x4 (acceso difícil, sendero empinado)",
    "estado_camino": "Caminos de lastre y senderos de montaña",
    "duracion_estimada": "Día completo (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Guía local obligatorio, calzado de montaña, repelente de insectos, suficiente agua",
    "enlace_web": null,
    "reserva_requerida": true,
    "horario_atencion": "Coordinación con guía local",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL002",
    "relevancia_cultural": "Catarata de difícil acceso en la región de La Fortuna, atractivo para excursionistas experimentados"
  },
  {
    "destination_id": "1fc1f83f-03fe-4c96-b3cb-a9a0595110f3",
    "expected_name": "Catarata La Paz Waterfall Gardens",
    "source_id": "nuevo_4",
    "tipo_acceso": "Carro normal (acceso pavimentado hasta el parque)",
    "estado_camino": "Carretera pavimentada y senderos bien mantenidos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado antideslizante, protección solar, no tocar animales",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 5:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL003",
    "relevancia_cultural": "Complejo ecoturístico con cataratas y santuarios de animales en la ruta a La Fortuna"
  },
  {
    "destination_id": "45688e18-9f24-4b5f-b324-34a478a1f6d2",
    "expected_name": "Catarata Opendola",
    "source_id": "nuevo_5",
    "tipo_acceso": "Carro normal (acceso cercano, caminata corta)",
    "estado_camino": "Camino de lastre y sendero corto",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado cómodo, protección solar, precaución en rocas húmedas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU001",
    "relevancia_cultural": "Catarata pintoresca en bosque seco, ideal para refrescarse en Guanacaste"
  },
  {
    "destination_id": "afe982d6-2bcc-4fce-8fa2-3d17a5ce29ee",
    "expected_name": "Cavernas de Venado",
    "source_id": "nuevo_6",
    "tipo_acceso": "4x4 (acceso a zona rural)",
    "estado_camino": "Camino de lastre y senderos de montaña",
    "duracion_estimada": "Medio día (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa de cambio, calzado de agua, linterna, buena condición física",
    "enlace_web": null,
    "reserva_requerida": true,
    "horario_atencion": "8:00 a.m. - 3:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL004",
    "relevancia_cultural": "Sistema de cuevas kársticas con espeleología auténtica en la Zona Norte"
  },
  {
    "destination_id": "4b7fb57a-7d3a-4682-9e89-0f64ffc14835",
    "expected_name": "Centro de Rescate Las Pumas (Cañas)",
    "source_id": "nuevo_7",
    "tipo_acceso": "Carro normal (acceso pavimentado)",
    "estado_camino": "Carretera pavimentada y senderos dentro del centro",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Todo el año",
    "recomendaciones_seguridad": "No alimentar a los animales, respetar las barreras de seguridad",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "GU002",
    "relevancia_cultural": "Centro de rehabilitación de fauna silvestre con enfoque educativo en Guanacaste"
  },
  {
    "destination_id": "7c972607-b322-44e8-aba3-f8358e09d021",
    "expected_name": "Cerro Amigos (Mirador Monteverde)",
    "source_id": "nuevo_8",
    "tipo_acceso": "4x4 (acceso a zona montañosa)",
    "estado_camino": "Camino de lastre y sendero empinado",
    "duracion_estimada": "Día completo (excursionistas)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa abrigada, calzado de montaña, bastones, suficiente agua y alimento",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "PN001",
    "relevancia_cultural": "Mirador emblemático con vista 360° de Monteverde y el Golfo de Nicoya"
  },
  {
    "destination_id": "ed8912bc-b01c-41fe-b08e-3d6ee4831c6e",
    "expected_name": "Isla Chira (Golfo de Nicoya)",
    "source_id": "nuevo_9",
    "tipo_acceso": "Lancha (acceso marítimo desde Puntarenas)",
    "estado_camino": "Caminos rurales y senderos en la isla",
    "duracion_estimada": "Día completo (turismo comunitario)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Chaleco salvavidas, protección solar, repelente de insectos",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Coordinación con comunidades locales",
    "estacionamiento": "Sí (en el muelle de Puntarenas)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "PU001",
    "relevancia_cultural": "Destino de turismo rural comunitario con tradiciones pesqueras en el Golfo de Nicoya"
  },
  {
    "destination_id": "6c24c898-2a98-4b86-bdc1-af950bb36e53",
    "expected_name": "Lago Arenal (Represa)",
    "source_id": "nuevo_10",
    "tipo_acceso": "Carro normal (acceso pavimentado)",
    "estado_camino": "Carretera pavimentada y accesos a distintos puntos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Chaleco salvavidas para deportes acuáticos, protección solar",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (en varios puntos)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (en zonas designadas)",
    "codigo_local": "AL005",
    "relevancia_cultural": "Embalse icónico con vistas al Volcán Arenal, centro de deportes acuáticos"
  },
  {
    "destination_id": "6f546a5a-0c36-4baf-8c24-d3f41cb5f145",
    "expected_name": "Las Hornillas Geothermal Park",
    "source_id": "nuevo_11",
    "tipo_acceso": "4x4 (acceso a zona volcánica)",
    "estado_camino": "Camino de lastre y senderos internos",
    "duracion_estimada": "Medio día (experiencia geotermal)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa de cambio, calzado cerrado, protección solar, hidratación",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "GU003",
    "relevancia_cultural": "Parque geotermal con baños de barro volcánico en las faldas del Miravalles"
  },
  {
    "destination_id": "886f1226-92cd-4748-ab78-68a06b001d4e",
    "expected_name": "Mercado Central de San José",
    "source_id": "nuevo_12",
    "tipo_acceso": "Carro normal (acceso urbano pavimentado)",
    "estado_camino": "Calles pavimentadas en San José",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Todo el año",
    "recomendaciones_seguridad": "Cuidado con pertenencias, no llevar objetos de valor",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "6:30 a.m. - 5:00 p.m.",
    "estacionamiento": "Sí (públicos cercanos)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "SJ001",
    "relevancia_cultural": "Corazón gastronómico y cultural de San José, fundado en 1880"
  },
  {
    "destination_id": "7c4b512f-accb-4f4b-b21e-8541c1548191",
    "expected_name": "Mirador de Orosi",
    "source_id": "nuevo_13",
    "tipo_acceso": "Carro normal (acceso pavimentado)",
    "estado_camino": "Carretera pavimentada hasta el mirador",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado con niños cerca del borde",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "CA001",
    "relevancia_cultural": "Mirador panorámico del Valle de Orosi, ideal para picnics familiares"
  },
  {
    "destination_id": "534056b5-bffa-4621-8b09-7f44015c3f8f",
    "expected_name": "Museo del Oro Precolombino",
    "source_id": "nuevo_14",
    "tipo_acceso": "Carro normal (acceso urbano pavimentado)",
    "estado_camino": "Calles pavimentadas en San José",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Todo el año",
    "recomendaciones_seguridad": "Cuidado con pertenencias en el centro de San José",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "9:00 a.m. - 5:00 p.m.",
    "estacionamiento": "Sí (públicos cercanos)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Sí (accesible)",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "SJ002",
    "relevancia_cultural": "Colección de orfebrería prehispánica en el subsuelo de la Plaza de la Cultura"
  },
  {
    "destination_id": "5fe2bb28-f908-4fde-84b0-31845ed903b3",
    "expected_name": "Parque Nacional Guanacaste (Sector Junquillal)",
    "source_id": "nuevo_15",
    "tipo_acceso": "Carro normal (acceso pavimentado a sector)",
    "estado_camino": "Carretera pavimentada y senderos internos",
    "duracion_estimada": "Día completo (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, repelente de insectos, suficiente agua",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU004",
    "relevancia_cultural": "Bosque seco tropical con playa y sitio de anidación de tortugas marinas"
  },
  {
    "destination_id": "5348f4c1-8357-43d8-9bb6-2e1f2153d772",
    "expected_name": "Parque Nacional Irazú (Cráter Principal)",
    "source_id": "nuevo_16",
    "tipo_acceso": "Carro normal (acceso pavimentado hasta el cráter)",
    "estado_camino": "Carretera pavimentada y senderos internos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa abrigada, protección solar, suficiente agua, cuidado en el borde del cráter",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 3:30 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "CA002",
    "relevancia_cultural": "Volcán con cráter de laguna verde, vista a dos océanos en días claros"
  },
  {
    "destination_id": "d2ff6614-0fbb-4a2f-8546-694d016f9e22",
    "expected_name": "Parque Nacional Marino Las Baulas (Playa Grande)",
    "source_id": "nuevo_17",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, respetar las zonas de anidación, chaleco salvavidas para surf",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "GU005",
    "relevancia_cultural": "Área protegida para anidación de tortuga baula, la más grande del mundo"
  },
  {
    "destination_id": "0e9f1614-d0da-4b50-af1a-19eed64d70fc",
    "expected_name": "Parque Nacional Santa Rosa (Sector Cocalino / Héroes)",
    "source_id": "nuevo_18",
    "tipo_acceso": "4x4 (acceso a playa y zona histórica)",
    "estado_camino": "Caminos de lastre y senderos internos",
    "duracion_estimada": "Día completo (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, repelente de insectos, suficiente agua, precaución en el mar",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU006",
    "relevancia_cultural": "Sitio histórico de la Batalla de Santa Rosa y famosa Roca Bruja para surf"
  },
  {
    "destination_id": "90168df9-d141-4ff5-9683-49b6e1ff3517",
    "expected_name": "Parque Nacional Volcán Arenal",
    "source_id": "nuevo_19",
    "tipo_acceso": "Carro normal (acceso pavimentado al parque)",
    "estado_camino": "Carretera pavimentada y senderos bien mantenidos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado cerrado, repelente de insectos, suficiente agua",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL006",
    "relevancia_cultural": "Ícono de Costa Rica, senderos por selva tropical y antiguos flujos de lava"
  },
  {
    "destination_id": "99d9908b-a8f2-482b-b36b-5faee279c84e",
    "expected_name": "Parque Nacional Volcán Miravalles",
    "source_id": "nuevo_20",
    "tipo_acceso": "4x4 (acceso a zona volcánica)",
    "estado_camino": "Caminos de lastre y senderos de montaña",
    "duracion_estimada": "Día completo (excursionistas)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa abrigada, calzado de montaña, suficiente agua y alimento",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU007",
    "relevancia_cultural": "Volcán menos visitado, con ecosistemas de bosque muy húmedo a nuboso"
  },
  {
    "destination_id": "a7bc2b3b-8fd3-44c8-a263-477f937b3021",
    "expected_name": "Parque Nacional Volcán Rincón de la Vieja",
    "source_id": "nuevo_21",
    "tipo_acceso": "4x4 (acceso a zona volcánica activa)",
    "estado_camino": "Caminos de lastre y senderos internos",
    "duracion_estimada": "Día completo (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado cerrado, protección solar, suficiente agua, respetar áreas de actividad volcánica",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU008",
    "relevancia_cultural": "Volcán activo con fumarolas, cataratas termales y diversidad de paisajes"
  },
  {
    "destination_id": "92bb87bb-e42a-415d-b468-50be2b62ba18",
    "expected_name": "Paseo de los Turistas (Puntarenas)",
    "source_id": "nuevo_22",
    "tipo_acceso": "Carro normal (acceso urbano pavimentado)",
    "estado_camino": "Calles pavimentadas en Puntarenas",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado con el tráfico",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (público)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Sí (accesible)",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "PU002",
    "relevancia_cultural": "Malecón emblemático con gastronomía marina y punto de salida a tours por el Golfo"
  },
  {
    "destination_id": "8c5902bc-5b1e-4477-973f-ec5995513c91",
    "expected_name": "Playa Cocles",
    "source_id": "nuevo_23",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, precaución con las olas, respeto a la vida marina",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "LI001",
    "relevancia_cultural": "Playa de arena blanca y aguas turquesas, famosa por surf en la costa caribeña"
  },
  {
    "destination_id": "26f2a11c-0886-4a9d-93db-cc052b12fc54",
    "expected_name": "Playa Danta y Dantita",
    "source_id": "nuevo_24",
    "tipo_acceso": "Carro normal (acceso pavimentado a la península)",
    "estado_camino": "Carretera pavimentada y accesos internos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado al nadar en zonas rocosas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU009",
    "relevancia_cultural": "Playas gemelas con aguas cristalinas en la Península de Papagayo"
  },
  {
    "destination_id": "81598a1c-680e-4066-a9d6-9eef7f0b786b",
    "expected_name": "Playa Garza",
    "source_id": "nuevo_25",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, precaución con corrientes marinas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": false,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU010",
    "relevancia_cultural": "Playa familiar con tradición pesquera artesanal en Nicoya"
  },
  {
    "destination_id": "60ed13c3-a610-4d42-a551-242db34155d8",
    "expected_name": "Playa Guiones",
    "source_id": "nuevo_26",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, respeto a las reglas de surf, cuidado con corrientes",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU011",
    "relevancia_cultural": "Playa famosa por surf y ambiente de bienestar en Nosara"
  },
  {
    "destination_id": "0a67fcab-9e5a-456f-8c45-f40008bc8467",
    "expected_name": "Playa Hermosa (Guanacaste)",
    "source_id": "nuevo_27",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, precaución al nadar",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU012",
    "relevancia_cultural": "Playa de arena oscura en bahía protegida, ideal para familias"
  },
  {
    "destination_id": "036b75cf-b194-4445-be8c-eb670cb10421",
    "expected_name": "Playa Junquillal",
    "source_id": "nuevo_28",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, precaución con oleaje fuerte",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU013",
    "relevancia_cultural": "Playa extensa con ambiente tranquilo y sitio de anidación de tortugas"
  },
  {
    "destination_id": "3c522d26-fee4-415e-9284-6763a83a3ccd",
    "expected_name": "Playa Langosta",
    "source_id": "nuevo_29",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, precaución al nadar en pozas de marea",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU014",
    "relevancia_cultural": "Playa exclusiva al sur de Tamarindo, ideal para snorkel"
  },
  {
    "destination_id": "e15772f9-e498-469d-98b3-c71b90c0bf19",
    "expected_name": "Playa Naranjo / Roca Bruja",
    "source_id": "nuevo_30",
    "tipo_acceso": "4x4 (acceso remoto y difícil)",
    "estado_camino": "Caminos de lastre y senderos en parque nacional",
    "duracion_estimada": "Día completo (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Vehiculo 4x4, suficiente agua y comida, protección solar",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU015",
    "relevancia_cultural": "Playa remota en Santa Rosa, famosa por la Roca Bruja para surf de clase mundial"
  },
  {
    "destination_id": "706178a4-1fa7-46d6-89eb-2cf6adfca3fb",
    "expected_name": "Playa Negra",
    "source_id": "nuevo_31",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, respeto a las reglas de surf",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": false,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU016",
    "relevancia_cultural": "Playa de arena negra con oleaje consistente para surfistas"
  },
  {
    "destination_id": "cbdf2e14-283c-4cc4-b333-c2070d6da084",
    "expected_name": "Playa Nosara y Pelada",
    "source_id": "nuevo_32",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado con corrientes marinas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU017",
    "relevancia_cultural": "Playa tranquila y centro de retiros de yoga y vida saludable"
  },
  {
    "destination_id": "27d30b09-3423-40c9-8ad4-ad87629e8326",
    "expected_name": "Playa Ocotal",
    "source_id": "nuevo_33",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, precaución al hacer snorkel",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": false,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU018",
    "relevancia_cultural": "Playa con snorkel desde la orilla y ambiente íntimo en Guanacaste"
  },
  {
    "destination_id": "58e6e984-102e-4b29-8efd-f7a1bf2438da",
    "expected_name": "Playa Sámara",
    "source_id": "nuevo_34",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado al nadar en zonas protegidas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU019",
    "relevancia_cultural": "Playa familiar con aguas tranquilas y ambiente de pueblo pesquero"
  },
  {
    "destination_id": "2948830e-6cb2-4e1b-bc5f-528e66d9f3ad",
    "expected_name": "Playa San Miguel y Coyote",
    "source_id": "nuevo_35",
    "tipo_acceso": "4x4 (acceso a playas remotas)",
    "estado_camino": "Caminos de lastre y accesos a la playa",
    "duracion_estimada": "Día completo (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, suficiente agua y comida, precaución con oleaje fuerte",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "GU020",
    "relevancia_cultural": "Playas vírgenes en la Península de Nicoya, para desconexión total"
  },
  {
    "destination_id": "6255a13f-4a71-4a43-b811-607c30fbe7eb",
    "expected_name": "Playa Tamarindo",
    "source_id": "nuevo_36",
    "tipo_acceso": "Carro normal (acceso pavimentado a la playa)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado con el tráfico en la zona",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "GU021",
    "relevancia_cultural": "Destino playero popular con vida nocturna y excelente surf"
  },
  {
    "destination_id": "dee4df23-7e17-4496-8378-b99d223057a2",
    "expected_name": "Pozas Azules de Río Agrio",
    "source_id": "nuevo_37",
    "tipo_acceso": "4x4 (acceso a zona montañosa)",
    "estado_camino": "Camino de lastre y senderos internos",
    "duracion_estimada": "Medio día (experiencia de aventura)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado antideslizante, protección solar, repelente de insectos",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL007",
    "relevancia_cultural": "Pozas de color turquesa por minerales volcánicos en Bajos del Toro"
  },
  {
    "destination_id": "4e66c108-7ed0-4265-b12c-41ca17547271",
    "expected_name": "Proyecto Asís (Centro de Rescate)",
    "source_id": "nuevo_38",
    "tipo_acceso": "Carro normal (acceso pavimentado al centro)",
    "estado_camino": "Carretera pavimentada y senderos internos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Todo el año",
    "recomendaciones_seguridad": "No tocar los animales, respetar las indicaciones del guía",
    "enlace_web": null,
    "reserva_requerida": true,
    "horario_atencion": "Coordinación con el centro",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL008",
    "relevancia_cultural": "Santuario de vida silvestre con enfoque educativo en la Zona Norte"
  },
  {
    "destination_id": "7cc91f6c-81a4-475b-8f76-640d84bbe216",
    "expected_name": "Refugio Nacional de Vida Silvestre Ostional",
    "source_id": "nuevo_39",
    "tipo_acceso": "Carro normal (acceso pavimentado al refugio)",
    "estado_camino": "Carretera pavimentada y accesos a la playa",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril), temporada de anidación",
    "recomendaciones_seguridad": "Protección solar, respetar las zonas de anidación, no usar flash en fotos",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "GU022",
    "relevancia_cultural": "Sitio de anidación de tortuga lora con fenómeno de 'arribada'"
  },
  {
    "destination_id": "4d287a05-ab6a-4172-930f-1ae7280a3a6d",
    "expected_name": "Reserva Biológica Caño Negro",
    "source_id": "nuevo_40",
    "tipo_acceso": "Lancha (acceso fluvial desde el pueblo)",
    "estado_camino": "Río y lagunas, senderos terrestres limitados",
    "duracion_estimada": "Día completo (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Chaleco salvavidas, protección solar, repelente de insectos",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (en el pueblo)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL009",
    "relevancia_cultural": "Humedal de importancia internacional para observación de aves acuáticas"
  },
  {
    "destination_id": "c4449fdb-0f4c-49b4-9389-504edecacafc",
    "expected_name": "Reserva Santa Elena",
    "source_id": "nuevo_41",
    "tipo_acceso": "Carro normal (acceso pavimentado a la reserva)",
    "estado_camino": "Carretera pavimentada y senderos bien mantenidos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa abrigada, calzado cerrado, repelente de insectos",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "7:00 a.m. - 4:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "PN002",
    "relevancia_cultural": "Bosque nuboso con torre de observación y avistamiento de quetzales"
  },
  {
    "destination_id": "19f22053-3581-44a3-9cee-4e1a6025dbdc",
    "expected_name": "Río Chollín (Termales Gratuitas Tabacón)",
    "source_id": "nuevo_42",
    "tipo_acceso": "Carro normal (acceso cercano, caminata corta)",
    "estado_camino": "Camino de lastre y sendero corto",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado antideslizante, protección solar, cuidado en rocas resbalosas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "AL010",
    "relevancia_cultural": "Opción gratuita y auténtica para baños termales cerca de Tabacón"
  },
  {
    "destination_id": "0302a0ee-f48f-428a-a2d5-d2d5986a42ee",
    "expected_name": "Ruinas de Ujarrás y Mirador",
    "source_id": "nuevo_43",
    "tipo_acceso": "Carro normal (acceso pavimentado)",
    "estado_camino": "Carretera pavimentada hasta las ruinas",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado al caminar en áreas históricas",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "No",
    "codigo_local": "CA003",
    "relevancia_cultural": "Ruinas coloniales con mirador panorámico del Valle de Orosi"
  },
  {
    "destination_id": "73c70ca5-4437-4e5c-964a-3edea8c86142",
    "expected_name": "San Gerardo de Dota (Avistamiento de Quetzales)",
    "source_id": "nuevo_44",
    "tipo_acceso": "Carro normal (acceso pavimentado a la zona)",
    "estado_camino": "Carretera pavimentada y senderos internos",
    "duracion_estimada": "Día completo (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa abrigada, calzado de montaña, binoculares",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "SJ003",
    "relevancia_cultural": "Mejor lugar del mundo para avistar el resplandeciente quetzal"
  },
  {
    "destination_id": "a5e9d74a-399c-43ce-a634-929ac33d9ba5",
    "expected_name": "Teatro Nacional de Costa Rica",
    "source_id": "nuevo_45",
    "tipo_acceso": "Carro normal (acceso urbano pavimentado)",
    "estado_camino": "Calles pavimentadas en San José",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Todo el año",
    "recomendaciones_seguridad": "Cuidado con pertenencias en el centro de San José",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "9:00 a.m. - 5:00 p.m.",
    "estacionamiento": "Sí (públicos cercanos)",
    "servicios_sanitarios": true,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "Sí (accesible)",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "SJ004",
    "relevancia_cultural": "Joya arquitectónica y cultural, sede de las artes escénicas del país"
  },
  {
    "destination_id": "5600ca34-2f45-43d7-86d6-6df202b7ba0b",
    "expected_name": "Termales de San Carlos (La Marina)",
    "source_id": "nuevo_46",
    "tipo_acceso": "Carro normal (acceso pavimentado al complejo)",
    "estado_camino": "Carretera pavimentada y accesos internos",
    "duracion_estimada": "Medio día (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Protección solar, cuidado en áreas de piscinas, supervisión de niños",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "10:00 a.m. - 8:00 p.m.",
    "estacionamiento": "Sí",
    "servicios_sanitarios": true,
    "restaurante_o_soda": true,
    "acceso_para_discapacitados": "Parcialmente accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "No",
    "codigo_local": "AL011",
    "relevancia_cultural": "Complejo termal familiar en la Zona Norte, conocido como 'La Marina'"
  },
  {
    "destination_id": "f5504c6b-1d94-49a1-bee0-c6e2e6aa20b4",
    "expected_name": "Valle de Bajos del Toro",
    "source_id": "nuevo_47",
    "tipo_acceso": "Carro normal (acceso pavimentado a la zona)",
    "estado_camino": "Carretera pavimentada y senderos internos",
    "duracion_estimada": "Día completo (apto para familias)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Calzado antideslizante, repelente de insectos, suficiente agua",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "Acceso libre durante el día",
    "estacionamiento": "Sí (en distintos puntos)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "Sí (con supervisión)",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "AL012",
    "relevancia_cultural": "Valle montañoso con cataratas de color turquesa, 'tierra de las cataratas azules'"
  },
  {
    "destination_id": "265b68c2-77d1-412e-aa44-1517119f90d7",
    "expected_name": "Volcán Barva (PN Braulio Carrillo)",
    "source_id": "nuevo_48",
    "tipo_acceso": "4x4 (acceso a zona montañosa)",
    "estado_camino": "Camino de lastre y senderos empinados",
    "duracion_estimada": "Día completo (excursionistas)",
    "mejor_temporada": "Época seca (diciembre a abril)",
    "recomendaciones_seguridad": "Ropa abrigada, calzado de montaña, suficiente agua y alimento",
    "enlace_web": null,
    "reserva_requerida": false,
    "horario_atencion": "8:00 a.m. - 3:00 p.m.",
    "estacionamiento": "Sí (básico)",
    "servicios_sanitarios": false,
    "restaurante_o_soda": false,
    "acceso_para_discapacitados": "No accesible",
    "se_permite_mascotas": "No",
    "camping_permitido": "Sí (con reserva)",
    "codigo_local": "SJ005",
    "relevancia_cultural": "Volcán con laguna de cráter verde en el Parque Nacional Braulio Carrillo"
  }
]$correct_visit_info$::jsonb)
  as item(
    destination_id uuid,
    expected_name text,
    source_id text,
    tipo_acceso text,
    estado_camino text,
    duracion_estimada text,
    mejor_temporada text,
    recomendaciones_seguridad text,
    enlace_web text,
    reserva_requerida boolean,
    horario_atencion text,
    estacionamiento text,
    servicios_sanitarios boolean,
    restaurante_o_soda boolean,
    acceso_para_discapacitados text,
    se_permite_mascotas text,
    camping_permitido text,
    codigo_local text,
    relevancia_cultural text
  );

create temporary table wrong_destination_visit_info_restore_payload (
  destination_id uuid primary key,
  tipo_acceso text,
  estado_camino text,
  duracion_estimada text,
  mejor_temporada text,
  recomendaciones_seguridad text,
  enlace_web text,
  reserva_requerida boolean,
  horario_atencion text,
  estacionamiento text,
  servicios_sanitarios boolean,
  restaurante_o_soda boolean,
  acceso_para_discapacitados text,
  se_permite_mascotas text,
  camping_permitido text,
  codigo_local text,
  relevancia_cultural text
) on commit drop;

insert into wrong_destination_visit_info_restore_payload
select
  backup.destination_id, backup.snapshot->>'tipo_acceso', backup.snapshot->>'estado_camino',
  backup.snapshot->>'duracion_estimada', backup.snapshot->>'mejor_temporada',
  backup.snapshot->>'recomendaciones_seguridad', backup.snapshot->>'enlace_web',
  (backup.snapshot->>'reserva_requerida')::boolean, backup.snapshot->>'horario_atencion',
  backup.snapshot->>'estacionamiento', (backup.snapshot->>'servicios_sanitarios')::boolean,
  (backup.snapshot->>'restaurante_o_soda')::boolean, backup.snapshot->>'acceso_para_discapacitados',
  backup.snapshot->>'se_permite_mascotas', backup.snapshot->>'camping_permitido',
  backup.snapshot->>'codigo_local', backup.snapshot->>'relevancia_cultural'
from private.destination_visit_info_backups backup
where backup.batch_key = '20260903_recovered_visit_info';

do $$
begin
  if (select count(*) from correct_destination_visit_info_payload) <> 48 then
    raise exception 'Expected 48 correct visit-information records';
  end if;
  if (select count(*) from wrong_destination_visit_info_restore_payload) <> 23 then
    raise exception 'Expected the 23-row backup from the mistaken import';
  end if;
  if (select count(*)
      from correct_destination_visit_info_payload payload
      join public.destinations destination
        on destination.id = payload.destination_id
       and destination.name = payload.expected_name
       and destination.status = 'Activo') <> 48 then
    raise exception 'All 48 correct visit-information targets must remain active and match their expected names';
  end if;
  if exists (
    select 1
    from correct_destination_visit_info_payload correct
    join wrong_destination_visit_info_restore_payload wrong on wrong.destination_id = correct.destination_id
  ) then
    raise exception 'The mistaken-import and correct-import destination sets must be disjoint';
  end if;
end
$$;

insert into private.destination_visit_info_backups (batch_key, destination_id, snapshot)
select '20260903_before_correct_48_visit_info', visit_info.destination_id, to_jsonb(visit_info)
from public.destination_visit_info visit_info
where visit_info.destination_id in (
  select destination_id from wrong_destination_visit_info_restore_payload
  union
  select destination_id from correct_destination_visit_info_payload
)
on conflict (batch_key, destination_id) do nothing;

insert into public.destination_visit_info (
  destination_id, tipo_acceso, estado_camino, duracion_estimada, mejor_temporada,
  recomendaciones_seguridad, enlace_web, reserva_requerida, horario_atencion, estacionamiento,
  servicios_sanitarios, restaurante_o_soda, acceso_para_discapacitados, se_permite_mascotas,
  camping_permitido, codigo_local, relevancia_cultural
)
select
  destination_id, tipo_acceso, estado_camino, duracion_estimada, mejor_temporada,
  recomendaciones_seguridad, enlace_web, reserva_requerida, horario_atencion, estacionamiento,
  servicios_sanitarios, restaurante_o_soda, acceso_para_discapacitados, se_permite_mascotas,
  camping_permitido, codigo_local, relevancia_cultural
from wrong_destination_visit_info_restore_payload
on conflict (destination_id) do update set
  tipo_acceso = excluded.tipo_acceso,
  estado_camino = excluded.estado_camino,
  duracion_estimada = excluded.duracion_estimada,
  mejor_temporada = excluded.mejor_temporada,
  recomendaciones_seguridad = excluded.recomendaciones_seguridad,
  enlace_web = excluded.enlace_web,
  reserva_requerida = excluded.reserva_requerida,
  horario_atencion = excluded.horario_atencion,
  estacionamiento = excluded.estacionamiento,
  servicios_sanitarios = excluded.servicios_sanitarios,
  restaurante_o_soda = excluded.restaurante_o_soda,
  acceso_para_discapacitados = excluded.acceso_para_discapacitados,
  se_permite_mascotas = excluded.se_permite_mascotas,
  camping_permitido = excluded.camping_permitido,
  codigo_local = excluded.codigo_local,
  relevancia_cultural = excluded.relevancia_cultural,
  updated_at = now();

insert into public.destination_visit_info (
  destination_id, tipo_acceso, estado_camino, duracion_estimada, mejor_temporada,
  recomendaciones_seguridad, enlace_web, reserva_requerida, horario_atencion, estacionamiento,
  servicios_sanitarios, restaurante_o_soda, acceso_para_discapacitados, se_permite_mascotas,
  camping_permitido, codigo_local, relevancia_cultural
)
select
  destination_id, tipo_acceso, estado_camino, duracion_estimada, mejor_temporada,
  recomendaciones_seguridad, enlace_web, reserva_requerida, horario_atencion, estacionamiento,
  servicios_sanitarios, restaurante_o_soda, acceso_para_discapacitados, se_permite_mascotas,
  camping_permitido, codigo_local, relevancia_cultural
from correct_destination_visit_info_payload
on conflict (destination_id) do update set
  tipo_acceso = excluded.tipo_acceso,
  estado_camino = excluded.estado_camino,
  duracion_estimada = excluded.duracion_estimada,
  mejor_temporada = excluded.mejor_temporada,
  recomendaciones_seguridad = excluded.recomendaciones_seguridad,
  enlace_web = excluded.enlace_web,
  reserva_requerida = excluded.reserva_requerida,
  horario_atencion = excluded.horario_atencion,
  estacionamiento = excluded.estacionamiento,
  servicios_sanitarios = excluded.servicios_sanitarios,
  restaurante_o_soda = excluded.restaurante_o_soda,
  acceso_para_discapacitados = excluded.acceso_para_discapacitados,
  se_permite_mascotas = excluded.se_permite_mascotas,
  camping_permitido = excluded.camping_permitido,
  codigo_local = excluded.codigo_local,
  relevancia_cultural = excluded.relevancia_cultural,
  updated_at = now();

do $$
begin
  if (select count(*)
      from public.destination_visit_info visit_info
      join wrong_destination_visit_info_restore_payload payload on payload.destination_id = visit_info.destination_id
      where visit_info.tipo_acceso is not distinct from payload.tipo_acceso
        and visit_info.estado_camino is not distinct from payload.estado_camino
        and visit_info.duracion_estimada is not distinct from payload.duracion_estimada
        and visit_info.mejor_temporada is not distinct from payload.mejor_temporada
        and visit_info.recomendaciones_seguridad is not distinct from payload.recomendaciones_seguridad
        and visit_info.enlace_web is not distinct from payload.enlace_web
        and visit_info.reserva_requerida is not distinct from payload.reserva_requerida
        and visit_info.horario_atencion is not distinct from payload.horario_atencion
        and visit_info.estacionamiento is not distinct from payload.estacionamiento
        and visit_info.servicios_sanitarios is not distinct from payload.servicios_sanitarios
        and visit_info.restaurante_o_soda is not distinct from payload.restaurante_o_soda
        and visit_info.acceso_para_discapacitados is not distinct from payload.acceso_para_discapacitados
        and visit_info.se_permite_mascotas is not distinct from payload.se_permite_mascotas
        and visit_info.camping_permitido is not distinct from payload.camping_permitido
        and visit_info.codigo_local is not distinct from payload.codigo_local
        and visit_info.relevancia_cultural is not distinct from payload.relevancia_cultural) <> 23 then
    raise exception 'Mistaken-import restoration verification failed';
  end if;

  if (select count(*)
      from public.destination_visit_info visit_info
      join correct_destination_visit_info_payload payload on payload.destination_id = visit_info.destination_id
      where visit_info.tipo_acceso is not distinct from payload.tipo_acceso
        and visit_info.estado_camino is not distinct from payload.estado_camino
        and visit_info.duracion_estimada is not distinct from payload.duracion_estimada
        and visit_info.mejor_temporada is not distinct from payload.mejor_temporada
        and visit_info.recomendaciones_seguridad is not distinct from payload.recomendaciones_seguridad
        and visit_info.enlace_web is not distinct from payload.enlace_web
        and visit_info.reserva_requerida is not distinct from payload.reserva_requerida
        and visit_info.horario_atencion is not distinct from payload.horario_atencion
        and visit_info.estacionamiento is not distinct from payload.estacionamiento
        and visit_info.servicios_sanitarios is not distinct from payload.servicios_sanitarios
        and visit_info.restaurante_o_soda is not distinct from payload.restaurante_o_soda
        and visit_info.acceso_para_discapacitados is not distinct from payload.acceso_para_discapacitados
        and visit_info.se_permite_mascotas is not distinct from payload.se_permite_mascotas
        and visit_info.camping_permitido is not distinct from payload.camping_permitido
        and visit_info.codigo_local is not distinct from payload.codigo_local
        and visit_info.relevancia_cultural is not distinct from payload.relevancia_cultural) <> 48 then
    raise exception 'Correct visit-information verification failed';
  end if;
end
$$;

commit;
